import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Photosgram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en" >
      <head></head>    
      <body>
        <main>
          <Navbar></Navbar>
          {children}  
        </main>     
      </body>
    </html>
  );
}
